name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq libfuse-dev ruby-dev libmbedtls-dev
    - name: Build
      run: |
        cmake .
        make VERBOSE=1
        make install
    - name: Test
      run: make travis-test

